name: custom-sklearn-env-v3
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - scikit-learn
    - pandas
    - mlflow==2.14.1
    - azureml-mlflow==1.55.0
    - matplotlib
    - azureml-sdk 
    - azureml-dataset-runtime